nodeLinker: node-modules
nmMode: hardlinks-local

yarnPath: .yarn/releases/yarn-3.3.0.cjs
npmScopes:
  smatch-corp:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN:-}
    npmPublishRegistry: 'https://npm.pkg.github.com'
    npmRegistryServer: 'https://npm.pkg.github.com'
