nmMode: hardlinks-local

nodeLinker: node-modules

npmScopes:
  smatch-corp:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
